apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-converter
  labels: { app: secure-converter }
spec:
  replicas: 2
  selector:
    matchLabels: { app: secure-converter }
  template:
    metadata:
      labels: { app: secure-converter }
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: secure-converter
          image: ghcr.io/kushaltalati/secure-converter:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8000, name: http }]
          env:
            - { name: HISTORY_SIZE, value: "20" }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          startupProbe:
            httpGet: { path: /health, port: http }
            failureThreshold: 15
            periodSeconds: 2
          readinessProbe:
            httpGet: { path: /ready, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 128Mi }
