#!/usr/bin/env bash
# 01-volumes: emptyDir, hostPath, static PV + PVC, StorageClass + dynamic provisioning.
. "$(dirname "$0")/lib.sh"
N=s13-volumes; K="kubectl -n $N"
ns_reset $N

hr "1. emptyDir - lives and dies with the Pod"
x "cat 01-volumes/emptydir-pod.yaml"
x "$K apply -f 01-volumes/emptydir-pod.yaml"
x "wait_ready $N emptydir-demo"
x "$K exec emptydir-demo -- sh -c 'echo \"Hello Kubernetes\" > /data/message.txt'"
x "$K exec emptydir-demo -- cat /data/message.txt"
x "$K exec emptydir-demo -- df -h /data | tail -1          # it is a directory on the node, not a separate disk"
x "$K get pod emptydir-demo -o jsonpath='{.spec.nodeName}{\"\\n\"}'"
hr "container restart (kill PID 1) keeps emptyDir, pod delete loses it"
x "$K exec emptydir-demo -- sh -c 'kill 1'; sleep 8; $K get pod emptydir-demo"
x "$K exec emptydir-demo -- cat /data/message.txt       # still there: same pod, new container"
x "$K delete pod emptydir-demo"
x "$K apply -f 01-volumes/emptydir-pod.yaml && wait_ready $N emptydir-demo"
x "$K exec emptydir-demo -- cat /data/message.txt       # gone: new pod = new emptyDir"

hr "2. hostPath - a directory on the node"
x "cat 01-volumes/hostpath-pod.yaml"
x "$K apply -f 01-volumes/hostpath-pod.yaml && wait_ready $N hostpath-demo"
x "$K exec hostpath-demo -- sh -c 'echo \"written by pod on \$(hostname)\" > /data/node-file.txt'"
x "$K get pod hostpath-demo -o wide --no-headers | awk '{print \"pod runs on node:\", \$7}'"
NODE=$($K get pod hostpath-demo -o jsonpath='{.spec.nodeName}')
x "docker exec $NODE ls -l /tmp/hostpath-data/ && docker exec $NODE cat /tmp/hostpath-data/node-file.txt    # visible on the kind node itself"
x "$K delete pod hostpath-demo"
hr "the same manifest, scheduled on the other worker: the directory there is empty"
OTHER=$(kubectl get nodes --no-headers -o custom-columns=N:.metadata.name | grep worker | grep -v "^$NODE$" | head -1)
x "awk -v n=$OTHER '/^spec:/{print; print \"  nodeName: \" n; next}1' 01-volumes/hostpath-pod.yaml | $K apply -f - && wait_ready $N hostpath-demo"
x "$K get pod hostpath-demo -o jsonpath='new pod runs on node: {.spec.nodeName}{\"\\n\"}'"
x "$K exec hostpath-demo -- cat /data/node-file.txt || echo '-> file missing: hostPath is a directory of ONE node'"
x "docker exec $OTHER ls -la /tmp/hostpath-data/"
hr "pinning the pod to the original node makes hostPath look persistent"
x "$K delete pod hostpath-demo --ignore-not-found >/dev/null; awk -v n=$NODE '/^spec:/{print; print \"  nodeName: \" n; next}1' 01-volumes/hostpath-pod.yaml | $K apply -f - && wait_ready $N hostpath-demo"
x "$K exec hostpath-demo -- cat /data/node-file.txt"
x "docker exec $NODE rm -rf /tmp/hostpath-data; docker exec $OTHER rm -rf /tmp/hostpath-data    # tidy the nodes"
x "$K delete pod hostpath-demo --wait=false"

hr "3. PersistentVolume + PersistentVolumeClaim (static provisioning)"
x "cat 02-persistent-storage/pv.yaml"
x "kubectl apply -f 02-persistent-storage/pv.yaml      # PVs are cluster-scoped, no namespace"
x "kubectl get pv student-pv"
x "cat 02-persistent-storage/pvc.yaml"
x "$K apply -f 02-persistent-storage/pvc.yaml"
x "sleep 3; $K get pvc student-pvc"
x "kubectl get pv student-pv"
hr "trap: the PVC has no storageClassName, so it got the DEFAULT class (standard) and is waiting for dynamic provisioning - it will never bind to my hand-made PV"
x "$K get pvc student-pvc -o jsonpath='storageClassName={.spec.storageClassName}{\"\\n\"}'"
x "$K delete pvc student-pvc"
x "sed 's/^spec:/spec:\n  storageClassName: \"\"/' 02-persistent-storage/pvc.yaml > /dev/null 2>&1; awk '/^spec:/{print; print \"  storageClassName: \\\"\\\"\"; next}1' 02-persistent-storage/pvc.yaml | tee /tmp/pvc-static-$$.yaml | $K apply -f -"
x "sleep 3; $K get pvc student-pvc"
x "kubectl get pv student-pv                           # Available -> Bound, CLAIM column filled"
x "$K apply -f 02-persistent-storage/pod.yaml && wait_ready $N storage-demo"
x "$K exec storage-demo -- sh -c 'echo \"Student: Kushal Talati 24BCS10123\" > /data/student-data.txt'"
x "$K exec storage-demo -- cat /data/student-data.txt"
x "$K delete pod storage-demo"
x "$K apply -f 02-persistent-storage/pod.yaml && wait_ready $N storage-demo"
x "$K exec storage-demo -- cat /data/student-data.txt   # survived the pod deletion"
x "$K get pod storage-demo -o jsonpath='pod is on: {.spec.nodeName}{\"\\n\"}'"
hr "capacity vs request: PVC asked for 500Mi, got the whole 1Gi PV"
x "$K get pvc student-pvc -o jsonpath='requested={.spec.resources.requests.storage} got={.status.capacity.storage}{\"\\n\"}'"
hr "reclaim policy Retain: deleting the PVC does not free the PV"
x "$K delete pod storage-demo && $K delete pvc student-pvc"
x "kubectl get pv student-pv                           # Released, not Available: the admin has to clean it"
x "$K apply -f /tmp/pvc-static-$$.yaml; sleep 5; $K get pvc student-pvc    # a new claim cannot bind to a Released PV"
x "kubectl describe pv student-pv | grep -E '^(Status|Claim)'"
x "$K delete pvc student-pvc; kubectl delete pv student-pv; rm -f /tmp/pvc-static-$$.yaml"

hr "4. StorageClass + dynamic provisioning"
x "kubectl get storageclass"
x "kubectl describe storageclass standard | grep -E '^(Name|IsDefaultClass|Provisioner|ReclaimPolicy|VolumeBindingMode)'"
x "cat 03-storageclass/pvc.yaml"
x "$K apply -f 03-storageclass/pvc.yaml"
x "sleep 3; $K get pvc dynamic-pvc"
x "$K describe pvc dynamic-pvc | grep -A3 '^Events'   # WaitForFirstConsumer: nothing happens until a pod uses it"
x "sed 's/student-pvc/dynamic-pvc/; s/storage-demo/dynamic-demo/' 02-persistent-storage/pod.yaml | $K apply -f -"
x "wait_ready $N dynamic-demo"
x "$K get pvc dynamic-pvc"
x "kubectl get pv | grep dynamic-pvc                   # the PV was created for me, name pvc-<uid>"
PV=$($K get pvc dynamic-pvc -o jsonpath='{.spec.volumeName}')
x "kubectl get pv $PV -o jsonpath='{.spec.local.path}{\"\\n\"}'"
x "kubectl -n local-path-storage logs deploy/local-path-provisioner | grep -i 'dynamic-pvc' | tail -3"
x "$K exec dynamic-demo -- sh -c 'echo dynamic > /data/d.txt'; $K delete pod dynamic-demo; sed 's/student-pvc/dynamic-pvc/; s/storage-demo/dynamic-demo/' 02-persistent-storage/pod.yaml | $K apply -f - >/dev/null; wait_ready $N dynamic-demo >/dev/null; $K exec dynamic-demo -- cat /data/d.txt"
hr "reclaim policy Delete: deleting the PVC deletes the PV too"
x "$K delete pod dynamic-demo && $K delete pvc dynamic-pvc"
x "sleep 5; kubectl get pv $PV 2>&1"

hr "cleanup"
x "kubectl delete ns $N --wait=false"
